project_name: "dcase_base"
language: python
entry_points:
  - /Users/takehonshion/work/iniad/dcase_base/DESED_task/dcase2024_task4_baseline
ignored_dirs:
  - node_modules
  - .git
  - dist
  - coverage
  - __pycache__
  - public/images  # 画像ディレクトリを除外
  - docs/pdfs      # PDFドキュメントを除外
ignored_files:
  - "*.log"
  - "*.tmp"
  - ".env*"
  - "*.jpg"
  - "*.png"
  - "*.pdf"
  - "*.zip"
max_file_size: 1048576  # 1MB（バイナリも含む総バイト数）
show_logs: true
use_lsp: true
read_only: true # 読み取り専用にする
web_dashboard_open_on_launch: false 
# セキュリティ設定
security:
  exclude_sensitive:
    - "**/*.key"
    - "**/*.pem"
    - "**/secrets/**"
  sanitize_logs: true
