pretrained:
  model: beats
  e2e: False
  freezed: True
  extracted_embeddings_dir: ./embeddings

cmt:
  enabled: False          # CMTを有効化
  phi_clip: 0.35 #0.5             # クリップレベル閾値 (論文では0.5)
  phi_frame: 0.35 #0.5          # フレームレベル閾値 (論文では0.5)

sebbs:
  enabled: false


training:  
  # バッチサイズ（論文推奨）
  batch_size: [12, 6, 6, 12, 24]    # [maestro, synth, strong, weak, unlabel]
  batch_size_val: 24
  
  # Mean Teacher設定
  ema_factor: 0.999
  self_sup_loss: bce
  
  # 損失重み調整
  const_max: 2                 # 自己教師学習最大重み
  n_epochs_warmup: 50               # ウォームアップ期間
  epoch_decay: 100
  
  # 訓練制御
  num_workers: 6
  n_epochs: 300
  early_stop_patience: 200
  accumulate_batches: 1
  gradient_clip: 5.0
  
  # 検証設定
  val_thresholds: [0.5]
  n_test_thresholds: 50
  validation_interval: 10
  
  # データ分割
  weak_split: 0.9
  maestro_split: 0.9
  
  # 再現性
  seed: 42
  deterministic: False
  precision: 32
  
  # データ拡張
  mixup: soft
  mixup_prob: 0.5
  
  # 評価メトリック
  obj_metric_synth_type: intersection
  obj_metric_maestro_type: fmo
  enable_progress_bar: True

scaler:
  statistic: instance
  normtype: minmax
  dims: [1, 2]
  savepath: ./scaler.ckpt

# データパス（既存設定をそのまま使用）
data:
  synth_folder: "/mnt/data/data/dcase/dataset/dcase_synth/audio/train/synthetic21_train/soundscapes_16k/"
  synth_folder_44k: "/mnt/data/data/dcase/dataset/dcase_synth/audio/train/synthetic21_train/soundscapes/"
  synth_tsv:  "/mnt/data/data/dcase/dataset/dcase_synth/metadata/train/synthetic21_train/soundscapes.tsv"
  strong_folder: "/mnt/data/data/dcase/dataset/audio/train/strong_label_real_16k/"
  strong_folder_44k: "/mnt/data/data/dcase/dataset/audio/train/strong_label_real/"
  strong_tsv: "/mnt/data/data/dcase/dataset/metadata/train/audioset_strong.tsv"
  synth_maestro_train: "/mnt/data/data/dcase/dataset/audio/maestro_synth_train_16k"
  synth_maestro_train_44k: "/mnt/data/data/dcase/dataset/audio/maestro_synth_train"
  synth_maestro_tsv: "/mnt/data/data/dcase/dataset/metadata/maestro_synth_train.tsv"
  real_maestro_train_folder: "/mnt/data/data/dcase/dataset/audio/maestro_real_train_16k"
  real_maestro_train_folder_44k: "/mnt/data/data/dcase/dataset/audio/maestro_real_train"
  real_maestro_train_tsv: "/mnt/data/data/dcase/dataset/metadata/maestro_real_train.tsv"
  real_maestro_val_folder: "/mnt/data/data/dcase/dataset/audio/maestro_real_validation_16k"
  real_maestro_val_folder_44k: "/mnt/data/data/dcase/dataset/audio/maestro_real_validation"
  real_maestro_val_tsv: "/mnt/data/data/dcase/dataset/metadata/maestro_real_validation.tsv"
  real_maestro_val_dur: "/mnt/data/data/dcase/dataset/metadata/maestro_real_durations.tsv"
  weak_folder: "/mnt/data/data/dcase/dataset/audio/train/weak_16k/"
  weak_folder_44k: "/mnt/data/data/dcase/dataset/audio/train/weak/"
  weak_tsv: "/mnt/data/data/dcase/dataset/metadata/train/weak.tsv"
  unlabeled_folder: "/mnt/data/data/dcase/dataset/audio/train/unlabel_in_domain_16k/"
  unlabeled_folder_44k: "/mnt/data/data/dcase/dataset/audio/train/unlabel_in_domain/"
  synth_val_folder: "/mnt/data/data/dcase/dataset/audio/validation/synthetic21_validation/soundscapes_16k/"
  synth_val_folder_44k: "/mnt/data/data/dcase/dataset/dcase_synth/audio/validation/synthetic21_validation/soundscapes/"
  synth_val_tsv:  "/mnt/data/data/dcase/dataset/dcase_synth/metadata/validation/synthetic21_validation/soundscapes.tsv"
  synth_val_dur: "/mnt/data/data/dcase/dataset/dcase_synth/metadata/validation/synthetic21_validation/durations.tsv"
  test_folder: "/mnt/data/data/dcase/dataset/audio/validation/validation_16k/"
  test_folder_44k: "/mnt/data/data/dcase/dataset/audio/validation/validation/"
  test_tsv: "/mnt/data/data/dcase/dataset/metadata/validation/validation.tsv"
  test_dur: "/mnt/data/data/dcase/dataset/metadata/validation/validation_durations.tsv"
  eval_folder: "/mnt/data/data/dcase/dataset/audio/eval24_16k"
  eval_folder_44k: "/mnt/data/data/dcase/dataset/audio/eval24"
  audio_max_len: 10
  fs: 16000
  net_subsample: 4

opt:
  lr: 0.001
  
feats:
  n_mels: 128
  n_filters: 2048
  hop_length: 256
  n_window: 2048
  sample_rate: 16000
  f_min: 0
  f_max: 8000

net:
  dropout: 0.2
  rnn_layers: 1
  n_in_channel: 1 # 3 #stack用に変更
  nclass: 27
  attention: True
  n_RNN_cell: 192
  activation: glu
  rnn_type: BGRU
  kernel_size: [3, 3, 3, 3, 3, 3, 3]
  padding: [1, 1, 1, 1, 1, 1, 1]
  stride: [1, 1, 1, 1, 1, 1, 1]
  nb_filters: [ 16, 32, 64, 128, 128, 128, 128 ]
  # MFCCは40, log melは128
  # pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 5 ], [ 1, 1 ], [ 1, 1 ], [ 1, 1 ] ] # for MFCC
  pooling:  [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ] # for log mel
  dropstep_recurrent: 0.3
  dropstep_recurrent_len: 16
  use_embeddings: True
  embedding_size: 768
  embedding_type: frame
  aggregation_type: pool1d
  specaugm_t_p: 0.0
  specaugm_t_l: 5
  specaugm_f_p: 0.0
  specaugm_f_l: 10
  median_filter: [3, 9, 9, 5, 5, 5, 9, 7, 11, 9, 7, 3, 9, 13, 7, 1, 13, 3, 13, 7, 5, 5, 1, 13, 17, 13, 15]
  # wandb
  use_wandb: True
  wandb_dir: "any"
  # for MixStyle
  attn_type: default
  attn_deepen: true
  mixstyle_type: resMix
